# Generated by Django 5.0 on 2023-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_profile_email_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio",
            new_name="alamat",
        ),
        migrations.AddField(
            model_name="profile",
            name="email_address",
            field=models.CharField(
                max_length=55, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="nis",
            field=models.CharField(
                max_length=55, null=True, unique=True, verbose_name="NIS"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="no_hp",
            field=models.CharField(
                max_length=55, null=True, unique=True, verbose_name="Mo HP"
            ),
        ),
    ]
